### ISSUE TITLE
Does Not Work When Opening Stream-Pi on MacOS Ventura 

### ISSUE THREAD

**Issue by TheNoob123-code** [Stream-Pi/Server#112]
Hi, after I finished the download for the snapshot version of Stream-Pi-Server for MacOS Ventura and opened Stream-Pi Server it gives me an error saying “‘Stream-Pi Server’ is damaged and can’t be opened. You should move it to the Trash.” I have tried methods that would fix the application, but they never worked. Does someone have a solution to this? I also tried the current download as well and it came up with the same error.

**Comment by TheNoob123-code** [comment]
I solved the issue.

**Comment by andreamarz** [comment]
Hi, how did you manage to solve the problem?

**Comment by TheNoob123-code** [comment]
> Hi, how did you manage to solve the problem?
The issue was occurring because the macs privacy and security system was not allowing me to open it, because it did not recognize the developer for stream pi. So I figured out that if you click cancel on the prompt and open up system preferences and go to Privacy and Security and then scroll down until you see a button with info above that says “open anyway” and that’s how I solved the issue.
