### ISSUE TITLE
Create ".exe" files for all Windows x86 versions of Stream-Pi [Server]

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/server#23]
Currently the "Stream-Pi Server" & "Stream-Pi Client" builds for Windows x86 platforms are distributed as a "VBScript" inside of a zipped folder structure.

This does not make for a user-friendly experience and it creates additional support requirements for end-users that could otherwise be completely eradicated if we simply released the program as a ".exe" file for the Windows x86 platform.

**Comment by rnayabed** [comment]
Not possible now due to limitations to `jpackage`. Will be done in the future

**Comment by rnayabed** [comment]
This is actually possible.

**Comment by THWExtreme** [comment]
Hi everybody,
I have made an installer for the StreamPi Server on Windows. It´s x86 compatible and include a auto shortcut on startmenu and Desktop. I have made that with [Install Forge](https://installforge.net/download/). 
The file is to big to upload it on GitHub i store it on my Website: [https://lucathomas.de/data/Stream%20Pi%20Server%20exe.zip](https://lucathomas.de/data/Stream%20Pi%20Server%20exe.zip)
Greetings
Luca-Alexander Thomas (THWExtreme)

**Comment by rnayabed** [comment]
That is quite nice, but unfortunately it seems that Install Forge is not an Opensource solution. In such cases, they can go ahead and put in malware/virus and we wouldnt ever know. Also it breaks the entire point of going 100% opensource. An exe alternative with pure java `jpackage` tool is in the works, and will be ready within a few weeks.

**Comment by TOGLK** [comment]
> Hi everybody,
> I have made an installer for the StreamPi Server on Windows. It´s x86 compatible and include a auto shortcut on startmenu and Desktop. I have made that with [Install Forge](https://installforge.net/download/).
> The file is to big to upload it on GitHub i store it on my Website: https://lucathomas.de/data/Stream%20Pi%20Server%20exe.zip
> Greetings
> Luca-Alexander Thomas (THWExtreme)

This doesn't align with the goals of the Stream-Pi Project.
Stream-Pi is focused on providing a FOSS experience, that means FREE & OPEN-SOURCE, however as has been noted above, "Install Forge" is NOT FOSS.

We only distribute changes that we have been verified in-house and meet the projects FOSS criteria, neither of which your suggested change aligns with.

We mean no offence by this, but we simply cannot back such modifications to the project as they go wholly against our ethos of being Open-Source and free to all, as in, Free Beer.


Also, as we cannot verify the safety of the file you are sharing I MUST make a public warning.
I hope you understand this and can respect that we must put our users safety first.

***The Stream-Pi Project and it's Team Members are not associated with and cannot verify the safety of 3rd-Party files***
***Download Un-Verified FIles at your OWN RISK. We accept NO RESPONSIBILITY***
***You have been WARNED!***

**Comment by rnayabed** [comment]
Done
