### ISSUE TITLE
StreamPi has problems with "СУКА БЛЯТЬ"

### ISSUE THREAD

**Issue by JannesStroehlein** [stream-pi/server#25]
Hello,

I wanted to add a TextBlock action to paste "СУКА БЛЯТЬ" (I'm not Russian so I have to Google every time to get the Cyrillic Version of cyka blyat). As I pressed to Icon on my RasPi I got this error message:
![image](https://user-images.githubusercontent.com/48127946/109613967-34d6b680-7b32-11eb-92b3-08ac3538f411.png)

Also my Windows Key stop working and caps got activated permanently. The PRINT key didn't work too. I had to kill the StreamPi server with the task manager.

**Comment by rnayabed** [comment]
Thanks for pointing this issue. Can you please make an issue on essentialactions repository, with the title "Support Foreign Keys for TextBlockAction" ?

**Comment by rnayabed** [comment]
Closing this as this is not related to server, but is a bug in textblockaction from stream-pi/essentialactions
