### ISSUE TITLE
Add ToggleAction

### ISSUE THREAD

**Issue by rnayabed** [stream-pi/server#28]

**Comment by sahmed007** [comment]
Hello, I'd like to work on this. Can you please provide me some more detail on what exactly needs to be done?

**Comment by rnayabed** [comment]
Currently the project itself is very young, to a point that there is virtually no documentation available for the APIs. even the javadoc isnt done.
I am currently busy till 18th due to exams so things are kind of at a standstill, but you can play around with the code and learn it yourself.

**Comment by rnayabed** [comment]
Closing due to no comment in past 24 hours. Reopen if needed.

**Comment by rnayabed** [comment]
done
