### ISSUE TITLE
[Cross-Platform][Feature Request] Add action to trigger "connect to obs websocket" 

### ISSUE THREAD

**Issue by sranjb2** [stream-pi/server#31]
currently, there is a "connect at startup" option for obs but if the streampi is running before obs then you must connect manually, adding an option to trigger the "connect to obs" action via a hotkey would be a QoL change

**Comment by rnayabed** [comment]
Duplicate. This is has already been opened [here](https://github.com/stream-pi/essentialactions/issues/18)

**Comment by sranjb2** [comment]
okay thank you, i didn't see it when i posted this sorry
