### ISSUE TITLE
[Windows x64] [Other] [Distributed Files] The current ZIP file for the Stream-Pi Server for Windows (x86-64) (Ver.1.0.0+EA2) contains a unnecessary JRE directory!

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/server#32]
============================================================================================================================================================================================================
**Target Platform:**
Windows x86-64

**Is this a Bug-Fix, Feature Request, or, Other?:**
Other

**What Platforms (Operating Systems) Were Used?:**
**(Host) Server** - Stream-Pi Server for Windows (x86) Ver.1.0.0 EA2 - Windows 10 (x86-64)
**(Guest) Client** - Not Applicable

**Describe the Issue:**
The currently distributed ZIP file for *Stream-Pi Server for Windows x86-64* contains a additional `JRE` directory that is surplus to the requirements to the software. Because of it's inclusion the size of the *Windows x86-64* ZIP file is roughly twice that of the equivalent *Stream-Pi Server for Linux x86-64* ZIP file that is also currently being distributed.
Please see the attached screenshot for further details: https://i.imgur.com/yhoaCz2.jpg 

**What Solution do you suggest to Resolve the Issue?:**
Remove the offending `JRE` directory and re-upload the *Stream-Pi Server for Windows x86-64* ZIP file to the GitHub download page.

**Who was the Issue initially reported by?:**
An Unknown User from the Stream-Pi Official Discord Server.

**Date of the Initial Report:**
13th of March, 2021 (2021-03-13)

============================================================================================================================================================================================================

***Do you have concerns about the details of this GitHub Issue? If you do then please comment below, Or, Contact me directly via GitHub/Discord/Element.io***

#### Contact Details:
Discord - TOGLK
Element.io (Matrix) - TOGLK
GitHub - TOGLK

**Comment by rnayabed** [comment]
The `jre` directory contains the prebundled custom Java Runtime which was generated using `jlink`. This runtime is used to run the Stream-Pi Software itself.

However, thanks to this issue, another DLL Bug was solved, for windows.
