### ISSUE TITLE
F-Secure Flagging This

### ISSUE THREAD

**Issue by swanserquack** [stream-pi/server#34]
Hi There,
After downloading the server and running run.vbs F-Secure proceeded to block it saying it was Trojan:W32/Kavala.UA. I put the file into VirusTotal and came back with no result. I have now sent this to F-Secure for them to analyze it and hopefully remove it from their database. My question is do you guys have any idea why my antivirus flagged this?
Thanks,
swanserquack

**Comment by rnayabed** [comment]
Thats ridiculous. You can go through the script itself and see that it does absolutely nothing malicious. 

From the next build onwards we will be shifting to EXEs for windows and AppImages for Linux, so hopefully this problem should not occur anymore.

**Comment by swanserquack** [comment]
Okay thanks!

**Comment by rnayabed** [comment]
Will close when builds will release with EXE/AppImage

**Comment by swanserquack** [comment]
Hey there @rnayabed. Didn't see a point in starting a new issue but just to let you know that on windows the default application for port 2004 is winstore.exe so you have to kill it in task manager otherwise the server will not let you into the port.

**Comment by rnayabed** [comment]
Try with a default port in Settings. 2005? 2006?

**Comment by swanserquack** [comment]
Nope I just killed the process and then changed the port. Just letting you know so you  are aware of it.

**Comment by rnayabed** [comment]
This issue has been fixed, and will not appear in EA+3
