### ISSUE TITLE
[LATEST SOURCE BUILD] If the server streches over a certain resolution. things will start to turn white

### ISSUE THREAD

**Issue by quimodotcom** [stream-pi/server#41]

**Comment by rnayabed** [comment]
Can you record a video/gif and send it here?

**Comment by quimodotcom** [comment]
Sure hold on. I’ll send it via discord dms

**Comment by EVNPC** [comment]
Turns out it was just a out of date library. false alarm

**Comment by rnayabed** [comment]
> Turns out it was just a out of date library. false alarm

Can you elaborate on which library?

**Comment by EVNPC** [comment]
com.gluonhq.util

**Comment by rnayabed** [comment]
> gluonhq util

Are you sure util was causing that? Util has nothing to do with the UI itself though

**Comment by quimodotcom** [comment]
I think it was something to do with something I had installed on my pc...

**Comment by rnayabed** [comment]
@quimodotcom should i close this? This has been stale

**Comment by rnayabed** [comment]
Closing as this has been left for over 20 days
