### ISSUE TITLE
toggle Buttons exp. for mute/unmute Source

### ISSUE THREAD

**Issue by PipeL1n3** [stream-pi/server#60]
It would be a charm to have a button that toggles a OBS source mute and unmute with giving a visual feedback (as in toggling the icon as well).
At the Moment i have to create 2 Panel-Buttons for each Source to Mute/Unmute it. (one with a logo as activated and one with a logo inactivated).

I am aware this means the state of the source has to be extracted from OBS to do so, to let it become in sync with obs at all time.
Should be manageable with websocket.

**Comment by rnayabed** [comment]
This has already been implemented and should be available from the next public release.
