### ISSUE TITLE
Use Class names instead of Module names to store UI components

### ISSUE THREAD

**Issue by dmf444** [stream-pi/server#67]
As part of my ongoing poking at the API, I noticed that once 2 functional modules were added to a single jar, the server component started to issue the commands to the incorrect action.

Interested in why it was happening, I poked around in the source to find the 'bug'. Here's what I found:

- Module Name is the same because it's in the same package, therefore ExternalPlugin#getPluginByModuleName will return the first plugin registered to that module
- This isn't ideal... it allows for some pretty bad issues with "standard design" ie, module can contain multiple providers, but the app won't handle it.

So I made a quick poke, some small code and hopefully this will start a positive conversation!

Here's my 'fix':

ExternalPlugins.java
```java    
public ExternalPlugin getPluginByModuleName(String name)
    {
        logger.info("Plugin being requested : "+name);
        Integer index = externalPluginsHashmap.getOrDefault(name, -1);
        if(index != -1)
        {
            return externalPlugins.get(index);
        }

        if(name.contains("class")){
            for (ExternalPlugin plugin: externalPlugins) {
                if(plugin.getClass().toString().equals(name)){
                    return plugin;
                }
            }
        }

        return null;
    }
```
ClientConnection.java (line 774)
`a.add(action.getClass().toString());`

PluginsPane.java(line 138)
`content.put(ActionDataFormats.MODULE_NAME, eachAction.getClass().toString());`

What it does? Instead of using the Module name, it uses Class Name. Class names should be Unique, and can be used by all levels of the app... i think :)

I implemented this in a cloned dev environment. Didn't see any issues, but only did a quick test.

**Comment by rnayabed** [comment]
This sounds like a good idea. I will be testing with this personally with all the possible scenarios and will get back to this.

**Comment by rnayabed** [comment]
This has been already implemented. Action unique IDs are now `<parent module name>.<canonical class name>`
