### ISSUE TITLE
Error loading plugins config.xml. Cannot continue.

### ISSUE THREAD

**Issue by sleiman** [stream-pi/server#70]
I try a factory reset using the interface, it's giving me this error even after reinstalling. Any ideas?

**Comment by rnayabed** [comment]
Which version? Also, can you try deleting the "Stream-Pi" directory from your user home folder ? (Windows: C:\Users\username\Stream-Pi)

**Comment by sleiman** [comment]
Thank you for your help @rnayabed ! Deleting the Stream-Pi folder from user home folder fixed the issue.

I am running version 1.0.0 Windows Early Access.

I tried doing a Factory Reset, it failed and when I restarted the app, I started getting that error message.

**Comment by rnayabed** [comment]
By Early Access do you mean EA+3 or EA+4-SNAPSHOT? Does it have a build date time?

**Comment by sleiman** [comment]
Server 1.0.0 EA 3

Here's a screenshot for build time 
![image](https://user-images.githubusercontent.com/1677407/125281535-5320a000-e2e4-11eb-9f18-5192dff50d20.png)
