### ISSUE TITLE
not a issue with software 

### ISSUE THREAD

**Issue by impulseoce** [stream-pi/server#77]
hi there i just need help. how do i connect obs socket to stream pi?

**Comment by rnayabed** [comment]
You will have to install the [OBS Websocket Plugin 4.9.1](https://github.com/Palakis/obs-websocket/releases/tag/4.9.1/) to your computer. Then configure it in your OBS by going to Plugins menu. 

After that back to stream-pi, you will have to go server settings> plugins> OBS and write down the url and password (if provided) to connect to your OBS
