### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by crackinx** [stream-pi/server#82]
There should be an option for the server to auto connect to a client, having to go into my PI and reconnect to the server every time my PC comes out of sleep is not super user friendly.  If I am missing something on how to go about this then instructions would be great! Other than that this is fantastic!!

**Comment by rnayabed** [comment]
Already implemented in client as "try connecting on action click" option in settings. If it is enabled, it will try to establish a connection with your server if you click an action without already being connected to the server.
