### ISSUE TITLE
Connected client not showing on Server app

### ISSUE THREAD

**Issue by andrisan** [stream-pi/server#84]
I tried to connect my phone using server IP/port information. 

The app on my phone shows that my phone is connected to the server. But the list of connected client in the server app is still empty.

Here's the information from the terminal:

![stream-pi](https://user-images.githubusercontent.com/10713658/143675026-51830f91-b6c3-4bb2-bfac-1f326c8d2759.png)

**Comment by rnayabed** [comment]
Make sure you are using the same version of Server and Client. (EA+3) 

It looks like you are using Server 1.0.0 EA+4 SNAPSHOT while your client is 1.0.0 EA+3 

Future releases will follow a far easier to follow naming convention.
