### ISSUE TITLE
Resetting to factory settings breaks config.xml

### ISSUE THREAD

**Issue by drsausages88** [stream-pi/server#86]
Hi team. i hit the reset button in the server settings to get rid of some pre-set buttons i have made and now i get the attached error whenever i try and open the server. 

i've uninstalled and reinstalled the program and cannot seem to get around this
![image](https://user-images.githubusercontent.com/94195046/145240747-19848cee-bfae-4b87-b0c7-fdde4eb4ce01.png)

**Comment by drsausages88** [comment]
OS: Windows 11

turns out i just needed to delete the existing config file in c:/users/[username]/stream-pi/server/ and it has started working again

**Comment by rnayabed** [comment]
The factory reset button is broken in EA+3. It has already been patched in the latest snapshots and will work in the future public releases.
