### ISSUE TITLE
Pasting Text Block numbers

### ISSUE THREAD

**Issue by Guesh1337** [stream-pi/server#88]
Hi, I would like to paste  letters and numbers using the Stream-Pi but Text Block only pastes Letters.
When I want to paste "123 TEST 123" it pastes "&é" TEST &é""
Is there any work around ? 
Thank you !

**Comment by rnayabed** [comment]
https://github.com/stream-pi/essential-actions/commit/0f280558d52224c435e15b468483e7ac445b51c9 fixes this.

These new actions are now available from Server snapshot build 395.
