### ISSUE TITLE
(Updated) Create Native Application Images for the following platforms:

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/server#9]
Linux x64, Linux aarch64, Windows x86, MacOS x86

**Comment by rnayabed** [comment]
server uses some AWT components. AWT isnt supported at all in graalvm jdk 11. will be done when graal based on jdk 17 is released

**Comment by rnayabed** [comment]
This cant be done in 1.0.0, unless they magically release graalvm based on jdk17 before jdk17 is even released

**Comment by SamuelQuinones** [comment]
Blocked by limitation of graalvm

**Comment by rnayabed** [comment]
Closing because this cannot be worked on until GraalVM native image allows dynamic code loading

**Comment by rnayabed** [comment]
Will open when it is possible.
