### ISSUE TITLE
Windows 10 Launching Stream Pi as a Background Process 

### ISSUE THREAD

**Issue by leappad** [stream-pi/server#92]
I go to launch the server software but when I launch it all it does is launch in the background, it's version 1.0 ea3 and there's no icon to open it as a window in the right of the taskbar. However the experimental 2.0 windows x86 version does run and works really nicely, I would use the 2.0 version but when I install the linux arm x32 version for the raspberry pi it seems to be missing java assets (I'll open an issue under the client github page).

**Comment by rnayabed** [comment]
Ill look into the client issue that you are having. It is not possible to backport the fix to 1.0.0 ea+3 because of lack of resources and will.
